# Generated by Django 6.0.8 on 2026-08-09 13:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
        ('profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('scholarship', 'Scholarship'), ('grant', 'Grant'), ('fellowship', 'Fellowship'), ('internship', 'Internship'), ('graduate_program', 'Graduate Program'), ('apprenticeship', 'Apprenticeship'), ('hackathon', 'Hackathon'), ('competition', 'Competition'), ('startup', 'Startup Competition'), ('workshop', 'Workshop'), ('conference', 'Conference'), ('volunteer', 'Volunteer Program'), ('leadership', 'Leadership Program'), ('other', 'Other')], max_length=50)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('deadline', models.DateTimeField()),
                ('application_url', models.URLField()),
                ('funding_type', models.CharField(choices=[('fully_funded', 'Fully Funded'), ('partially_funded', 'Partially Funded'), ('unfunded', 'Unfunded')], default='unfunded', max_length=30)),
                ('eligibility', models.TextField(blank=True)),
                ('requirements', models.TextField(blank=True)),
                ('benefits', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Verification'), ('verified', 'Verified'), ('reported', 'Reported'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunities', to='organization.organization')),
                ('skills', models.ManyToManyField(blank=True, related_name='opportunities', to='profiles.skill')),
            ],
        ),
        migrations.CreateModel(
            name='OpportunityReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='opportunities.opportunity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunity_reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
