# Generated by Django 6.0.8 on 2026-08-25 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0002_opportunity_external_id_opportunity_source_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
